pipeline {
    agent any

    stages {
        stage('Trigger Child Pipelines') {
            steps {
                script {
                    // Trigger multiple Jenkins pipelines
                    build job: 'DevOpsProj-QualityGate', wait: false
                    build job: 'DevOpsProj-PRCheck', wait: false
                }
            }
        }
    }
}
